plugins { id 'com.android.application' }
android {
    namespace 'com.example.calcpro'
    compileSdk 33
    defaultConfig { applicationId "com.example.calcpro"; minSdk 21; targetSdk 33 }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}